# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - name: run-editor
    init: npm run setup:editor 
    command: npm run start:editor
  - name: run-renderer 
    init: npm run setup:editor
    command: npm run start:renderer
ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001
    onOpen: open-browser
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: prevent-merge-on-error
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
